import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_DIR = path.join(__dirname, '../src/gasifiers_data');
const MANIFEST_PATH = path.join(__dirname, '../src/data/dataManifest.js');

function formatBytes(bytes, decimals = 1) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}

function getLabel(filename) {
    if (filename.toLowerCase().includes('early')) return 'Early Phase (10k)';
    if (filename.toLowerCase().includes('mid')) return 'Mid Phase (10k)';
    if (filename.toLowerCase().includes('late')) return 'Late Phase (10k)';
    return filename;
}

try {
    if (!fs.existsSync(DATA_DIR)) {
        console.error(`Directory not found: ${DATA_DIR}`);
        process.exit(1);
    }

    const folders = fs.readdirSync(DATA_DIR, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

    const manifestData = folders.map(folderName => {
        const folderPath = path.join(DATA_DIR, folderName);
        const files = fs.readdirSync(folderPath)
            .filter(file => file.endsWith('.csv'))
            .map(file => {
                const filePath = path.join(folderPath, file);
                const stats = fs.statSync(filePath);
                
                // Construct ID from filename (remove extension and common suffixes if needed, or just use filename)
                // Existing used e.g. G1_R20_early
                let id = file.replace('.csv', '');
                // Simple heuristic to shorten ID if it's very long
                if (id.includes('_10k_RIL_pipeline_cleaned')) {
                     id = id.replace('_10k_RIL_pipeline_cleaned', '');
                     id = id.replace('_RIL_pipeline_cleaned', ''); // fallback
                }

                return {
                    id: id,
                    name: file,
                    label: getLabel(file),
                    size: formatBytes(stats.size),
                    path: `/src/gasifiers_data/${folderName}/${file}`
                };
            });
        
        // Sort files to ensure Early -> Mid -> Late order if possible
        const order = { 'Early Phase (10k)': 1, 'Mid Phase (10k)': 2, 'Late Phase (10k)': 3 };
        files.sort((a, b) => (order[a.label] || 99) - (order[b.label] || 99));

        return {
            id: folderName,
            name: folderName,
            description: `Gasifier ${folderName.charAt(1)} - Run ${folderName.split('R')[1] || '?'}`,
            files: files
        };
    });

    const fileContent = `// Static manifest of available gasifier datasets
// This file is auto-generated by scripts/updateManifest.js
// Do not edit manually.

export const DATA_FOLDERS = ${JSON.stringify(manifestData, null, 2)};

// Helper to get import path for dynamic import
export function getImportPath(folderId, fileName) {
  return \`../gasifiers_data/\${folderId}/\${fileName}\`;
}
`;

    fs.writeFileSync(MANIFEST_PATH, fileContent);
    console.log(`Manifest updated at ${MANIFEST_PATH}`);
    console.log(`Found ${folders.length} datasets.`);

} catch (err) {
    console.error('Error updating manifest:', err);
    process.exit(1);
}
